# Site settings
title: Art by Nidhi
email: nidhismathur@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Artwork by Singapore based Nidhi Mathur (art_n_canvas).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nidhi.studio" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll
instagram_username: art_n_canvas

# Build settings
markdown: kramdown
permalink: pretty
