# Site settings
title: Popli Resource Group
email: info@popliresources.com
description: > # this means to ignore newlines until "baseurl:"
  Consturction machines sold by Popli Resources.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://popliresources.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty
